spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog_db
    username: root
    password: 数据库密码
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.qq.com
    port: 587
    username: 填写自己的QQ邮箱
    password: 邮箱授权密码
    default-encoding: UTF-8
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      debug: true
  data:
    redis:
      host: localhost
      port: 6379
      password: redis密码
      database: 0
  security:
    user:
      name: admin
      password: 设置密码

mybatis:
  type-aliases-package: com.example.blog.entity  # 实体类包路径
  mapper-locations: classpath:mapper/*.xml
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

